services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    container_name: mlflow-server
    platform: linux/amd64
    ports:
      - "5000:5000"  # Expose MLflow server on port 6565
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - BACKEND_STORE_URI=sqlite:///mlflow.db  # Using SQLite for simplicity
      - ARTIFACT_STORE=/mlflow/artifacts  # Store artifacts in a local directory
    volumes:
      - ./mlruns:/mlflow/artifacts  # Mount local artifact storage directory
      - ./mlflow.db:/mlflow/mlflow.db  # Mount SQLite database file
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

  nginx:
    image: nginx:latest
    container_name: nginx-mlflow
    ports:
      - "80:80"   # For HTTP traffic
      # - "443:443" # For HTTPS traffic (optional, requires SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # NGINX configuration file
      # - ./ssl:/etc/ssl:ro  # Optional: Mount SSL certificates for HTTPS